# Setup
title:        Josiah Kerley
tagline:      Senior Cloud Engineer, Nerd, Etc...
baseurl:      ""
commonurl:    "JosiahKerley.io"
paginate:     1

# About/contact
author:
  avatar:     /assets/img/personal/avatar.jpg
  name:       Josiah Kerley
  email:      josiahkerley@gmail.com
  url:        http://josiahkerley.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-asciinema

#Others
markdown: kramdown