# Setup
title:        Josiah Kerley
tagline:      Senior Cloud Engineer, Nerd, Etc...
baseurl:      "http://josiahkerley.io"
paginate:     1

# About/contact
author:
  name:       Josiah Kerley
  url:        http://josiahkerley.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown